/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StateStoreInspectorRouteImport } from './routes/state/store-inspector'
import { Route as StateStackedDeckRouteImport } from './routes/state/stacked-deck'
import { Route as StateScrollableTrayRouteImport } from './routes/state/scrollable-tray'
import { Route as StateOutsideReactRouteImport } from './routes/state/outside-react'
import { Route as StateMaxToastsRouteImport } from './routes/state/max-toasts'
import { Route as StateDuplicateIdRouteImport } from './routes/state/duplicate-id'
import { Route as RenderingTailwindStyledRouteImport } from './routes/rendering/tailwind-styled'
import { Route as RenderingCustomComponentRouteImport } from './routes/rendering/custom-component'
import { Route as RenderingAnimationWrapperRouteImport } from './routes/rendering/animation-wrapper'
import { Route as InlineMultipleContainersRouteImport } from './routes/inline/multiple-containers'
import { Route as InlineInlineSidebarRouteImport } from './routes/inline/inline-sidebar'
import { Route as InlineFormValidationRouteImport } from './routes/inline/form-validation'
import { Route as FundamentalsPromiseLifecycleRouteImport } from './routes/fundamentals/promise-lifecycle'
import { Route as FundamentalsPlacementsRouteImport } from './routes/fundamentals/placements'
import { Route as FundamentalsPersistentToastRouteImport } from './routes/fundamentals/persistent-toast'
import { Route as FundamentalsCountdownProgressRouteImport } from './routes/fundamentals/countdown-progress'
import { Route as FundamentalsBasicVariantsRouteImport } from './routes/fundamentals/basic-variants'
import { Route as AdvancedSwipePinDismissRouteImport } from './routes/advanced/swipe-pin-dismiss'
import { Route as AdvancedFramerMotionRouteImport } from './routes/advanced/framer-motion'
import { Route as AdvancedFloatingAnchorRouteImport } from './routes/advanced/floating-anchor'
import { Route as AdvancedDragToDismissRouteImport } from './routes/advanced/drag-to-dismiss'
import { Route as AdvancedDragRepositionRouteImport } from './routes/advanced/drag-reposition'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StateStoreInspectorRoute = StateStoreInspectorRouteImport.update({
  id: '/state/store-inspector',
  path: '/state/store-inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const StateStackedDeckRoute = StateStackedDeckRouteImport.update({
  id: '/state/stacked-deck',
  path: '/state/stacked-deck',
  getParentRoute: () => rootRouteImport,
} as any)
const StateScrollableTrayRoute = StateScrollableTrayRouteImport.update({
  id: '/state/scrollable-tray',
  path: '/state/scrollable-tray',
  getParentRoute: () => rootRouteImport,
} as any)
const StateOutsideReactRoute = StateOutsideReactRouteImport.update({
  id: '/state/outside-react',
  path: '/state/outside-react',
  getParentRoute: () => rootRouteImport,
} as any)
const StateMaxToastsRoute = StateMaxToastsRouteImport.update({
  id: '/state/max-toasts',
  path: '/state/max-toasts',
  getParentRoute: () => rootRouteImport,
} as any)
const StateDuplicateIdRoute = StateDuplicateIdRouteImport.update({
  id: '/state/duplicate-id',
  path: '/state/duplicate-id',
  getParentRoute: () => rootRouteImport,
} as any)
const RenderingTailwindStyledRoute = RenderingTailwindStyledRouteImport.update({
  id: '/rendering/tailwind-styled',
  path: '/rendering/tailwind-styled',
  getParentRoute: () => rootRouteImport,
} as any)
const RenderingCustomComponentRoute =
  RenderingCustomComponentRouteImport.update({
    id: '/rendering/custom-component',
    path: '/rendering/custom-component',
    getParentRoute: () => rootRouteImport,
  } as any)
const RenderingAnimationWrapperRoute =
  RenderingAnimationWrapperRouteImport.update({
    id: '/rendering/animation-wrapper',
    path: '/rendering/animation-wrapper',
    getParentRoute: () => rootRouteImport,
  } as any)
const InlineMultipleContainersRoute =
  InlineMultipleContainersRouteImport.update({
    id: '/inline/multiple-containers',
    path: '/inline/multiple-containers',
    getParentRoute: () => rootRouteImport,
  } as any)
const InlineInlineSidebarRoute = InlineInlineSidebarRouteImport.update({
  id: '/inline/inline-sidebar',
  path: '/inline/inline-sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const InlineFormValidationRoute = InlineFormValidationRouteImport.update({
  id: '/inline/form-validation',
  path: '/inline/form-validation',
  getParentRoute: () => rootRouteImport,
} as any)
const FundamentalsPromiseLifecycleRoute =
  FundamentalsPromiseLifecycleRouteImport.update({
    id: '/fundamentals/promise-lifecycle',
    path: '/fundamentals/promise-lifecycle',
    getParentRoute: () => rootRouteImport,
  } as any)
const FundamentalsPlacementsRoute = FundamentalsPlacementsRouteImport.update({
  id: '/fundamentals/placements',
  path: '/fundamentals/placements',
  getParentRoute: () => rootRouteImport,
} as any)
const FundamentalsPersistentToastRoute =
  FundamentalsPersistentToastRouteImport.update({
    id: '/fundamentals/persistent-toast',
    path: '/fundamentals/persistent-toast',
    getParentRoute: () => rootRouteImport,
  } as any)
const FundamentalsCountdownProgressRoute =
  FundamentalsCountdownProgressRouteImport.update({
    id: '/fundamentals/countdown-progress',
    path: '/fundamentals/countdown-progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const FundamentalsBasicVariantsRoute =
  FundamentalsBasicVariantsRouteImport.update({
    id: '/fundamentals/basic-variants',
    path: '/fundamentals/basic-variants',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdvancedSwipePinDismissRoute = AdvancedSwipePinDismissRouteImport.update({
  id: '/advanced/swipe-pin-dismiss',
  path: '/advanced/swipe-pin-dismiss',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedFramerMotionRoute = AdvancedFramerMotionRouteImport.update({
  id: '/advanced/framer-motion',
  path: '/advanced/framer-motion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedFloatingAnchorRoute = AdvancedFloatingAnchorRouteImport.update({
  id: '/advanced/floating-anchor',
  path: '/advanced/floating-anchor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedDragToDismissRoute = AdvancedDragToDismissRouteImport.update({
  id: '/advanced/drag-to-dismiss',
  path: '/advanced/drag-to-dismiss',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedDragRepositionRoute = AdvancedDragRepositionRouteImport.update({
  id: '/advanced/drag-reposition',
  path: '/advanced/drag-reposition',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advanced/drag-reposition': typeof AdvancedDragRepositionRoute
  '/advanced/drag-to-dismiss': typeof AdvancedDragToDismissRoute
  '/advanced/floating-anchor': typeof AdvancedFloatingAnchorRoute
  '/advanced/framer-motion': typeof AdvancedFramerMotionRoute
  '/advanced/swipe-pin-dismiss': typeof AdvancedSwipePinDismissRoute
  '/fundamentals/basic-variants': typeof FundamentalsBasicVariantsRoute
  '/fundamentals/countdown-progress': typeof FundamentalsCountdownProgressRoute
  '/fundamentals/persistent-toast': typeof FundamentalsPersistentToastRoute
  '/fundamentals/placements': typeof FundamentalsPlacementsRoute
  '/fundamentals/promise-lifecycle': typeof FundamentalsPromiseLifecycleRoute
  '/inline/form-validation': typeof InlineFormValidationRoute
  '/inline/inline-sidebar': typeof InlineInlineSidebarRoute
  '/inline/multiple-containers': typeof InlineMultipleContainersRoute
  '/rendering/animation-wrapper': typeof RenderingAnimationWrapperRoute
  '/rendering/custom-component': typeof RenderingCustomComponentRoute
  '/rendering/tailwind-styled': typeof RenderingTailwindStyledRoute
  '/state/duplicate-id': typeof StateDuplicateIdRoute
  '/state/max-toasts': typeof StateMaxToastsRoute
  '/state/outside-react': typeof StateOutsideReactRoute
  '/state/scrollable-tray': typeof StateScrollableTrayRoute
  '/state/stacked-deck': typeof StateStackedDeckRoute
  '/state/store-inspector': typeof StateStoreInspectorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advanced/drag-reposition': typeof AdvancedDragRepositionRoute
  '/advanced/drag-to-dismiss': typeof AdvancedDragToDismissRoute
  '/advanced/floating-anchor': typeof AdvancedFloatingAnchorRoute
  '/advanced/framer-motion': typeof AdvancedFramerMotionRoute
  '/advanced/swipe-pin-dismiss': typeof AdvancedSwipePinDismissRoute
  '/fundamentals/basic-variants': typeof FundamentalsBasicVariantsRoute
  '/fundamentals/countdown-progress': typeof FundamentalsCountdownProgressRoute
  '/fundamentals/persistent-toast': typeof FundamentalsPersistentToastRoute
  '/fundamentals/placements': typeof FundamentalsPlacementsRoute
  '/fundamentals/promise-lifecycle': typeof FundamentalsPromiseLifecycleRoute
  '/inline/form-validation': typeof InlineFormValidationRoute
  '/inline/inline-sidebar': typeof InlineInlineSidebarRoute
  '/inline/multiple-containers': typeof InlineMultipleContainersRoute
  '/rendering/animation-wrapper': typeof RenderingAnimationWrapperRoute
  '/rendering/custom-component': typeof RenderingCustomComponentRoute
  '/rendering/tailwind-styled': typeof RenderingTailwindStyledRoute
  '/state/duplicate-id': typeof StateDuplicateIdRoute
  '/state/max-toasts': typeof StateMaxToastsRoute
  '/state/outside-react': typeof StateOutsideReactRoute
  '/state/scrollable-tray': typeof StateScrollableTrayRoute
  '/state/stacked-deck': typeof StateStackedDeckRoute
  '/state/store-inspector': typeof StateStoreInspectorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advanced/drag-reposition': typeof AdvancedDragRepositionRoute
  '/advanced/drag-to-dismiss': typeof AdvancedDragToDismissRoute
  '/advanced/floating-anchor': typeof AdvancedFloatingAnchorRoute
  '/advanced/framer-motion': typeof AdvancedFramerMotionRoute
  '/advanced/swipe-pin-dismiss': typeof AdvancedSwipePinDismissRoute
  '/fundamentals/basic-variants': typeof FundamentalsBasicVariantsRoute
  '/fundamentals/countdown-progress': typeof FundamentalsCountdownProgressRoute
  '/fundamentals/persistent-toast': typeof FundamentalsPersistentToastRoute
  '/fundamentals/placements': typeof FundamentalsPlacementsRoute
  '/fundamentals/promise-lifecycle': typeof FundamentalsPromiseLifecycleRoute
  '/inline/form-validation': typeof InlineFormValidationRoute
  '/inline/inline-sidebar': typeof InlineInlineSidebarRoute
  '/inline/multiple-containers': typeof InlineMultipleContainersRoute
  '/rendering/animation-wrapper': typeof RenderingAnimationWrapperRoute
  '/rendering/custom-component': typeof RenderingCustomComponentRoute
  '/rendering/tailwind-styled': typeof RenderingTailwindStyledRoute
  '/state/duplicate-id': typeof StateDuplicateIdRoute
  '/state/max-toasts': typeof StateMaxToastsRoute
  '/state/outside-react': typeof StateOutsideReactRoute
  '/state/scrollable-tray': typeof StateScrollableTrayRoute
  '/state/stacked-deck': typeof StateStackedDeckRoute
  '/state/store-inspector': typeof StateStoreInspectorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advanced/drag-reposition'
    | '/advanced/drag-to-dismiss'
    | '/advanced/floating-anchor'
    | '/advanced/framer-motion'
    | '/advanced/swipe-pin-dismiss'
    | '/fundamentals/basic-variants'
    | '/fundamentals/countdown-progress'
    | '/fundamentals/persistent-toast'
    | '/fundamentals/placements'
    | '/fundamentals/promise-lifecycle'
    | '/inline/form-validation'
    | '/inline/inline-sidebar'
    | '/inline/multiple-containers'
    | '/rendering/animation-wrapper'
    | '/rendering/custom-component'
    | '/rendering/tailwind-styled'
    | '/state/duplicate-id'
    | '/state/max-toasts'
    | '/state/outside-react'
    | '/state/scrollable-tray'
    | '/state/stacked-deck'
    | '/state/store-inspector'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advanced/drag-reposition'
    | '/advanced/drag-to-dismiss'
    | '/advanced/floating-anchor'
    | '/advanced/framer-motion'
    | '/advanced/swipe-pin-dismiss'
    | '/fundamentals/basic-variants'
    | '/fundamentals/countdown-progress'
    | '/fundamentals/persistent-toast'
    | '/fundamentals/placements'
    | '/fundamentals/promise-lifecycle'
    | '/inline/form-validation'
    | '/inline/inline-sidebar'
    | '/inline/multiple-containers'
    | '/rendering/animation-wrapper'
    | '/rendering/custom-component'
    | '/rendering/tailwind-styled'
    | '/state/duplicate-id'
    | '/state/max-toasts'
    | '/state/outside-react'
    | '/state/scrollable-tray'
    | '/state/stacked-deck'
    | '/state/store-inspector'
  id:
    | '__root__'
    | '/'
    | '/advanced/drag-reposition'
    | '/advanced/drag-to-dismiss'
    | '/advanced/floating-anchor'
    | '/advanced/framer-motion'
    | '/advanced/swipe-pin-dismiss'
    | '/fundamentals/basic-variants'
    | '/fundamentals/countdown-progress'
    | '/fundamentals/persistent-toast'
    | '/fundamentals/placements'
    | '/fundamentals/promise-lifecycle'
    | '/inline/form-validation'
    | '/inline/inline-sidebar'
    | '/inline/multiple-containers'
    | '/rendering/animation-wrapper'
    | '/rendering/custom-component'
    | '/rendering/tailwind-styled'
    | '/state/duplicate-id'
    | '/state/max-toasts'
    | '/state/outside-react'
    | '/state/scrollable-tray'
    | '/state/stacked-deck'
    | '/state/store-inspector'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvancedDragRepositionRoute: typeof AdvancedDragRepositionRoute
  AdvancedDragToDismissRoute: typeof AdvancedDragToDismissRoute
  AdvancedFloatingAnchorRoute: typeof AdvancedFloatingAnchorRoute
  AdvancedFramerMotionRoute: typeof AdvancedFramerMotionRoute
  AdvancedSwipePinDismissRoute: typeof AdvancedSwipePinDismissRoute
  FundamentalsBasicVariantsRoute: typeof FundamentalsBasicVariantsRoute
  FundamentalsCountdownProgressRoute: typeof FundamentalsCountdownProgressRoute
  FundamentalsPersistentToastRoute: typeof FundamentalsPersistentToastRoute
  FundamentalsPlacementsRoute: typeof FundamentalsPlacementsRoute
  FundamentalsPromiseLifecycleRoute: typeof FundamentalsPromiseLifecycleRoute
  InlineFormValidationRoute: typeof InlineFormValidationRoute
  InlineInlineSidebarRoute: typeof InlineInlineSidebarRoute
  InlineMultipleContainersRoute: typeof InlineMultipleContainersRoute
  RenderingAnimationWrapperRoute: typeof RenderingAnimationWrapperRoute
  RenderingCustomComponentRoute: typeof RenderingCustomComponentRoute
  RenderingTailwindStyledRoute: typeof RenderingTailwindStyledRoute
  StateDuplicateIdRoute: typeof StateDuplicateIdRoute
  StateMaxToastsRoute: typeof StateMaxToastsRoute
  StateOutsideReactRoute: typeof StateOutsideReactRoute
  StateScrollableTrayRoute: typeof StateScrollableTrayRoute
  StateStackedDeckRoute: typeof StateStackedDeckRoute
  StateStoreInspectorRoute: typeof StateStoreInspectorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state/store-inspector': {
      id: '/state/store-inspector'
      path: '/state/store-inspector'
      fullPath: '/state/store-inspector'
      preLoaderRoute: typeof StateStoreInspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state/stacked-deck': {
      id: '/state/stacked-deck'
      path: '/state/stacked-deck'
      fullPath: '/state/stacked-deck'
      preLoaderRoute: typeof StateStackedDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state/scrollable-tray': {
      id: '/state/scrollable-tray'
      path: '/state/scrollable-tray'
      fullPath: '/state/scrollable-tray'
      preLoaderRoute: typeof StateScrollableTrayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state/outside-react': {
      id: '/state/outside-react'
      path: '/state/outside-react'
      fullPath: '/state/outside-react'
      preLoaderRoute: typeof StateOutsideReactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state/max-toasts': {
      id: '/state/max-toasts'
      path: '/state/max-toasts'
      fullPath: '/state/max-toasts'
      preLoaderRoute: typeof StateMaxToastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state/duplicate-id': {
      id: '/state/duplicate-id'
      path: '/state/duplicate-id'
      fullPath: '/state/duplicate-id'
      preLoaderRoute: typeof StateDuplicateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendering/tailwind-styled': {
      id: '/rendering/tailwind-styled'
      path: '/rendering/tailwind-styled'
      fullPath: '/rendering/tailwind-styled'
      preLoaderRoute: typeof RenderingTailwindStyledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendering/custom-component': {
      id: '/rendering/custom-component'
      path: '/rendering/custom-component'
      fullPath: '/rendering/custom-component'
      preLoaderRoute: typeof RenderingCustomComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendering/animation-wrapper': {
      id: '/rendering/animation-wrapper'
      path: '/rendering/animation-wrapper'
      fullPath: '/rendering/animation-wrapper'
      preLoaderRoute: typeof RenderingAnimationWrapperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inline/multiple-containers': {
      id: '/inline/multiple-containers'
      path: '/inline/multiple-containers'
      fullPath: '/inline/multiple-containers'
      preLoaderRoute: typeof InlineMultipleContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inline/inline-sidebar': {
      id: '/inline/inline-sidebar'
      path: '/inline/inline-sidebar'
      fullPath: '/inline/inline-sidebar'
      preLoaderRoute: typeof InlineInlineSidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inline/form-validation': {
      id: '/inline/form-validation'
      path: '/inline/form-validation'
      fullPath: '/inline/form-validation'
      preLoaderRoute: typeof InlineFormValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundamentals/promise-lifecycle': {
      id: '/fundamentals/promise-lifecycle'
      path: '/fundamentals/promise-lifecycle'
      fullPath: '/fundamentals/promise-lifecycle'
      preLoaderRoute: typeof FundamentalsPromiseLifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundamentals/placements': {
      id: '/fundamentals/placements'
      path: '/fundamentals/placements'
      fullPath: '/fundamentals/placements'
      preLoaderRoute: typeof FundamentalsPlacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundamentals/persistent-toast': {
      id: '/fundamentals/persistent-toast'
      path: '/fundamentals/persistent-toast'
      fullPath: '/fundamentals/persistent-toast'
      preLoaderRoute: typeof FundamentalsPersistentToastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundamentals/countdown-progress': {
      id: '/fundamentals/countdown-progress'
      path: '/fundamentals/countdown-progress'
      fullPath: '/fundamentals/countdown-progress'
      preLoaderRoute: typeof FundamentalsCountdownProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundamentals/basic-variants': {
      id: '/fundamentals/basic-variants'
      path: '/fundamentals/basic-variants'
      fullPath: '/fundamentals/basic-variants'
      preLoaderRoute: typeof FundamentalsBasicVariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/swipe-pin-dismiss': {
      id: '/advanced/swipe-pin-dismiss'
      path: '/advanced/swipe-pin-dismiss'
      fullPath: '/advanced/swipe-pin-dismiss'
      preLoaderRoute: typeof AdvancedSwipePinDismissRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/framer-motion': {
      id: '/advanced/framer-motion'
      path: '/advanced/framer-motion'
      fullPath: '/advanced/framer-motion'
      preLoaderRoute: typeof AdvancedFramerMotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/floating-anchor': {
      id: '/advanced/floating-anchor'
      path: '/advanced/floating-anchor'
      fullPath: '/advanced/floating-anchor'
      preLoaderRoute: typeof AdvancedFloatingAnchorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/drag-to-dismiss': {
      id: '/advanced/drag-to-dismiss'
      path: '/advanced/drag-to-dismiss'
      fullPath: '/advanced/drag-to-dismiss'
      preLoaderRoute: typeof AdvancedDragToDismissRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/drag-reposition': {
      id: '/advanced/drag-reposition'
      path: '/advanced/drag-reposition'
      fullPath: '/advanced/drag-reposition'
      preLoaderRoute: typeof AdvancedDragRepositionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvancedDragRepositionRoute: AdvancedDragRepositionRoute,
  AdvancedDragToDismissRoute: AdvancedDragToDismissRoute,
  AdvancedFloatingAnchorRoute: AdvancedFloatingAnchorRoute,
  AdvancedFramerMotionRoute: AdvancedFramerMotionRoute,
  AdvancedSwipePinDismissRoute: AdvancedSwipePinDismissRoute,
  FundamentalsBasicVariantsRoute: FundamentalsBasicVariantsRoute,
  FundamentalsCountdownProgressRoute: FundamentalsCountdownProgressRoute,
  FundamentalsPersistentToastRoute: FundamentalsPersistentToastRoute,
  FundamentalsPlacementsRoute: FundamentalsPlacementsRoute,
  FundamentalsPromiseLifecycleRoute: FundamentalsPromiseLifecycleRoute,
  InlineFormValidationRoute: InlineFormValidationRoute,
  InlineInlineSidebarRoute: InlineInlineSidebarRoute,
  InlineMultipleContainersRoute: InlineMultipleContainersRoute,
  RenderingAnimationWrapperRoute: RenderingAnimationWrapperRoute,
  RenderingCustomComponentRoute: RenderingCustomComponentRoute,
  RenderingTailwindStyledRoute: RenderingTailwindStyledRoute,
  StateDuplicateIdRoute: StateDuplicateIdRoute,
  StateMaxToastsRoute: StateMaxToastsRoute,
  StateOutsideReactRoute: StateOutsideReactRoute,
  StateScrollableTrayRoute: StateScrollableTrayRoute,
  StateStackedDeckRoute: StateStackedDeckRoute,
  StateStoreInspectorRoute: StateStoreInspectorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
