/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ExamplesTailwindStyledRouteImport } from "./routes/examples/tailwind-styled";
import { Route as ExamplesSwipePinDismissRouteImport } from "./routes/examples/swipe-pin-dismiss";
import { Route as ExamplesStoreInspectorRouteImport } from "./routes/examples/store-inspector";
import { Route as ExamplesStackedDeckRouteImport } from "./routes/examples/stacked-deck";
import { Route as ExamplesScrollableTrayRouteImport } from "./routes/examples/scrollable-tray";
import { Route as ExamplesPromiseLifecycleRouteImport } from "./routes/examples/promise-lifecycle";
import { Route as ExamplesPlacementsRouteImport } from "./routes/examples/placements";
import { Route as ExamplesPersistentToastRouteImport } from "./routes/examples/persistent-toast";
import { Route as ExamplesOutsideReactRouteImport } from "./routes/examples/outside-react";
import { Route as ExamplesMultipleContainersRouteImport } from "./routes/examples/multiple-containers";
import { Route as ExamplesMaxToastsRouteImport } from "./routes/examples/max-toasts";
import { Route as ExamplesInlineSidebarRouteImport } from "./routes/examples/inline-sidebar";
import { Route as ExamplesFramerMotionRouteImport } from "./routes/examples/framer-motion";
import { Route as ExamplesFormValidationRouteImport } from "./routes/examples/form-validation";
import { Route as ExamplesFloatingAnchorRouteImport } from "./routes/examples/floating-anchor";
import { Route as ExamplesDuplicateIdRouteImport } from "./routes/examples/duplicate-id";
import { Route as ExamplesDragToDismissRouteImport } from "./routes/examples/drag-to-dismiss";
import { Route as ExamplesDragRepositionRouteImport } from "./routes/examples/drag-reposition";
import { Route as ExamplesCustomComponentRouteImport } from "./routes/examples/custom-component";
import { Route as ExamplesCountdownProgressRouteImport } from "./routes/examples/countdown-progress";
import { Route as ExamplesBasicVariantsRouteImport } from "./routes/examples/basic-variants";
import { Route as ExamplesAnimationWrapperRouteImport } from "./routes/examples/animation-wrapper";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesTailwindStyledRoute = ExamplesTailwindStyledRouteImport.update({
  id: "/examples/tailwind-styled",
  path: "/examples/tailwind-styled",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesSwipePinDismissRoute = ExamplesSwipePinDismissRouteImport.update({
  id: "/examples/swipe-pin-dismiss",
  path: "/examples/swipe-pin-dismiss",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesStoreInspectorRoute = ExamplesStoreInspectorRouteImport.update({
  id: "/examples/store-inspector",
  path: "/examples/store-inspector",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesStackedDeckRoute = ExamplesStackedDeckRouteImport.update({
  id: "/examples/stacked-deck",
  path: "/examples/stacked-deck",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesScrollableTrayRoute = ExamplesScrollableTrayRouteImport.update({
  id: "/examples/scrollable-tray",
  path: "/examples/scrollable-tray",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesPromiseLifecycleRoute =
  ExamplesPromiseLifecycleRouteImport.update({
    id: "/examples/promise-lifecycle",
    path: "/examples/promise-lifecycle",
    getParentRoute: () => rootRouteImport,
  } as any);
const ExamplesPlacementsRoute = ExamplesPlacementsRouteImport.update({
  id: "/examples/placements",
  path: "/examples/placements",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesPersistentToastRoute = ExamplesPersistentToastRouteImport.update({
  id: "/examples/persistent-toast",
  path: "/examples/persistent-toast",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesOutsideReactRoute = ExamplesOutsideReactRouteImport.update({
  id: "/examples/outside-react",
  path: "/examples/outside-react",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesMultipleContainersRoute =
  ExamplesMultipleContainersRouteImport.update({
    id: "/examples/multiple-containers",
    path: "/examples/multiple-containers",
    getParentRoute: () => rootRouteImport,
  } as any);
const ExamplesMaxToastsRoute = ExamplesMaxToastsRouteImport.update({
  id: "/examples/max-toasts",
  path: "/examples/max-toasts",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesInlineSidebarRoute = ExamplesInlineSidebarRouteImport.update({
  id: "/examples/inline-sidebar",
  path: "/examples/inline-sidebar",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesFramerMotionRoute = ExamplesFramerMotionRouteImport.update({
  id: "/examples/framer-motion",
  path: "/examples/framer-motion",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesFormValidationRoute = ExamplesFormValidationRouteImport.update({
  id: "/examples/form-validation",
  path: "/examples/form-validation",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesFloatingAnchorRoute = ExamplesFloatingAnchorRouteImport.update({
  id: "/examples/floating-anchor",
  path: "/examples/floating-anchor",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesDuplicateIdRoute = ExamplesDuplicateIdRouteImport.update({
  id: "/examples/duplicate-id",
  path: "/examples/duplicate-id",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesDragToDismissRoute = ExamplesDragToDismissRouteImport.update({
  id: "/examples/drag-to-dismiss",
  path: "/examples/drag-to-dismiss",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesDragRepositionRoute = ExamplesDragRepositionRouteImport.update({
  id: "/examples/drag-reposition",
  path: "/examples/drag-reposition",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesCustomComponentRoute = ExamplesCustomComponentRouteImport.update({
  id: "/examples/custom-component",
  path: "/examples/custom-component",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesCountdownProgressRoute =
  ExamplesCountdownProgressRouteImport.update({
    id: "/examples/countdown-progress",
    path: "/examples/countdown-progress",
    getParentRoute: () => rootRouteImport,
  } as any);
const ExamplesBasicVariantsRoute = ExamplesBasicVariantsRouteImport.update({
  id: "/examples/basic-variants",
  path: "/examples/basic-variants",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesAnimationWrapperRoute =
  ExamplesAnimationWrapperRouteImport.update({
    id: "/examples/animation-wrapper",
    path: "/examples/animation-wrapper",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/examples/animation-wrapper": typeof ExamplesAnimationWrapperRoute;
  "/examples/basic-variants": typeof ExamplesBasicVariantsRoute;
  "/examples/countdown-progress": typeof ExamplesCountdownProgressRoute;
  "/examples/custom-component": typeof ExamplesCustomComponentRoute;
  "/examples/drag-reposition": typeof ExamplesDragRepositionRoute;
  "/examples/drag-to-dismiss": typeof ExamplesDragToDismissRoute;
  "/examples/duplicate-id": typeof ExamplesDuplicateIdRoute;
  "/examples/floating-anchor": typeof ExamplesFloatingAnchorRoute;
  "/examples/form-validation": typeof ExamplesFormValidationRoute;
  "/examples/framer-motion": typeof ExamplesFramerMotionRoute;
  "/examples/inline-sidebar": typeof ExamplesInlineSidebarRoute;
  "/examples/max-toasts": typeof ExamplesMaxToastsRoute;
  "/examples/multiple-containers": typeof ExamplesMultipleContainersRoute;
  "/examples/outside-react": typeof ExamplesOutsideReactRoute;
  "/examples/persistent-toast": typeof ExamplesPersistentToastRoute;
  "/examples/placements": typeof ExamplesPlacementsRoute;
  "/examples/promise-lifecycle": typeof ExamplesPromiseLifecycleRoute;
  "/examples/scrollable-tray": typeof ExamplesScrollableTrayRoute;
  "/examples/stacked-deck": typeof ExamplesStackedDeckRoute;
  "/examples/store-inspector": typeof ExamplesStoreInspectorRoute;
  "/examples/swipe-pin-dismiss": typeof ExamplesSwipePinDismissRoute;
  "/examples/tailwind-styled": typeof ExamplesTailwindStyledRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/examples/animation-wrapper": typeof ExamplesAnimationWrapperRoute;
  "/examples/basic-variants": typeof ExamplesBasicVariantsRoute;
  "/examples/countdown-progress": typeof ExamplesCountdownProgressRoute;
  "/examples/custom-component": typeof ExamplesCustomComponentRoute;
  "/examples/drag-reposition": typeof ExamplesDragRepositionRoute;
  "/examples/drag-to-dismiss": typeof ExamplesDragToDismissRoute;
  "/examples/duplicate-id": typeof ExamplesDuplicateIdRoute;
  "/examples/floating-anchor": typeof ExamplesFloatingAnchorRoute;
  "/examples/form-validation": typeof ExamplesFormValidationRoute;
  "/examples/framer-motion": typeof ExamplesFramerMotionRoute;
  "/examples/inline-sidebar": typeof ExamplesInlineSidebarRoute;
  "/examples/max-toasts": typeof ExamplesMaxToastsRoute;
  "/examples/multiple-containers": typeof ExamplesMultipleContainersRoute;
  "/examples/outside-react": typeof ExamplesOutsideReactRoute;
  "/examples/persistent-toast": typeof ExamplesPersistentToastRoute;
  "/examples/placements": typeof ExamplesPlacementsRoute;
  "/examples/promise-lifecycle": typeof ExamplesPromiseLifecycleRoute;
  "/examples/scrollable-tray": typeof ExamplesScrollableTrayRoute;
  "/examples/stacked-deck": typeof ExamplesStackedDeckRoute;
  "/examples/store-inspector": typeof ExamplesStoreInspectorRoute;
  "/examples/swipe-pin-dismiss": typeof ExamplesSwipePinDismissRoute;
  "/examples/tailwind-styled": typeof ExamplesTailwindStyledRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/examples/animation-wrapper": typeof ExamplesAnimationWrapperRoute;
  "/examples/basic-variants": typeof ExamplesBasicVariantsRoute;
  "/examples/countdown-progress": typeof ExamplesCountdownProgressRoute;
  "/examples/custom-component": typeof ExamplesCustomComponentRoute;
  "/examples/drag-reposition": typeof ExamplesDragRepositionRoute;
  "/examples/drag-to-dismiss": typeof ExamplesDragToDismissRoute;
  "/examples/duplicate-id": typeof ExamplesDuplicateIdRoute;
  "/examples/floating-anchor": typeof ExamplesFloatingAnchorRoute;
  "/examples/form-validation": typeof ExamplesFormValidationRoute;
  "/examples/framer-motion": typeof ExamplesFramerMotionRoute;
  "/examples/inline-sidebar": typeof ExamplesInlineSidebarRoute;
  "/examples/max-toasts": typeof ExamplesMaxToastsRoute;
  "/examples/multiple-containers": typeof ExamplesMultipleContainersRoute;
  "/examples/outside-react": typeof ExamplesOutsideReactRoute;
  "/examples/persistent-toast": typeof ExamplesPersistentToastRoute;
  "/examples/placements": typeof ExamplesPlacementsRoute;
  "/examples/promise-lifecycle": typeof ExamplesPromiseLifecycleRoute;
  "/examples/scrollable-tray": typeof ExamplesScrollableTrayRoute;
  "/examples/stacked-deck": typeof ExamplesStackedDeckRoute;
  "/examples/store-inspector": typeof ExamplesStoreInspectorRoute;
  "/examples/swipe-pin-dismiss": typeof ExamplesSwipePinDismissRoute;
  "/examples/tailwind-styled": typeof ExamplesTailwindStyledRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/examples/animation-wrapper"
    | "/examples/basic-variants"
    | "/examples/countdown-progress"
    | "/examples/custom-component"
    | "/examples/drag-reposition"
    | "/examples/drag-to-dismiss"
    | "/examples/duplicate-id"
    | "/examples/floating-anchor"
    | "/examples/form-validation"
    | "/examples/framer-motion"
    | "/examples/inline-sidebar"
    | "/examples/max-toasts"
    | "/examples/multiple-containers"
    | "/examples/outside-react"
    | "/examples/persistent-toast"
    | "/examples/placements"
    | "/examples/promise-lifecycle"
    | "/examples/scrollable-tray"
    | "/examples/stacked-deck"
    | "/examples/store-inspector"
    | "/examples/swipe-pin-dismiss"
    | "/examples/tailwind-styled";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/examples/animation-wrapper"
    | "/examples/basic-variants"
    | "/examples/countdown-progress"
    | "/examples/custom-component"
    | "/examples/drag-reposition"
    | "/examples/drag-to-dismiss"
    | "/examples/duplicate-id"
    | "/examples/floating-anchor"
    | "/examples/form-validation"
    | "/examples/framer-motion"
    | "/examples/inline-sidebar"
    | "/examples/max-toasts"
    | "/examples/multiple-containers"
    | "/examples/outside-react"
    | "/examples/persistent-toast"
    | "/examples/placements"
    | "/examples/promise-lifecycle"
    | "/examples/scrollable-tray"
    | "/examples/stacked-deck"
    | "/examples/store-inspector"
    | "/examples/swipe-pin-dismiss"
    | "/examples/tailwind-styled";
  id:
    | "__root__"
    | "/"
    | "/examples/animation-wrapper"
    | "/examples/basic-variants"
    | "/examples/countdown-progress"
    | "/examples/custom-component"
    | "/examples/drag-reposition"
    | "/examples/drag-to-dismiss"
    | "/examples/duplicate-id"
    | "/examples/floating-anchor"
    | "/examples/form-validation"
    | "/examples/framer-motion"
    | "/examples/inline-sidebar"
    | "/examples/max-toasts"
    | "/examples/multiple-containers"
    | "/examples/outside-react"
    | "/examples/persistent-toast"
    | "/examples/placements"
    | "/examples/promise-lifecycle"
    | "/examples/scrollable-tray"
    | "/examples/stacked-deck"
    | "/examples/store-inspector"
    | "/examples/swipe-pin-dismiss"
    | "/examples/tailwind-styled";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ExamplesAnimationWrapperRoute: typeof ExamplesAnimationWrapperRoute;
  ExamplesBasicVariantsRoute: typeof ExamplesBasicVariantsRoute;
  ExamplesCountdownProgressRoute: typeof ExamplesCountdownProgressRoute;
  ExamplesCustomComponentRoute: typeof ExamplesCustomComponentRoute;
  ExamplesDragRepositionRoute: typeof ExamplesDragRepositionRoute;
  ExamplesDragToDismissRoute: typeof ExamplesDragToDismissRoute;
  ExamplesDuplicateIdRoute: typeof ExamplesDuplicateIdRoute;
  ExamplesFloatingAnchorRoute: typeof ExamplesFloatingAnchorRoute;
  ExamplesFormValidationRoute: typeof ExamplesFormValidationRoute;
  ExamplesFramerMotionRoute: typeof ExamplesFramerMotionRoute;
  ExamplesInlineSidebarRoute: typeof ExamplesInlineSidebarRoute;
  ExamplesMaxToastsRoute: typeof ExamplesMaxToastsRoute;
  ExamplesMultipleContainersRoute: typeof ExamplesMultipleContainersRoute;
  ExamplesOutsideReactRoute: typeof ExamplesOutsideReactRoute;
  ExamplesPersistentToastRoute: typeof ExamplesPersistentToastRoute;
  ExamplesPlacementsRoute: typeof ExamplesPlacementsRoute;
  ExamplesPromiseLifecycleRoute: typeof ExamplesPromiseLifecycleRoute;
  ExamplesScrollableTrayRoute: typeof ExamplesScrollableTrayRoute;
  ExamplesStackedDeckRoute: typeof ExamplesStackedDeckRoute;
  ExamplesStoreInspectorRoute: typeof ExamplesStoreInspectorRoute;
  ExamplesSwipePinDismissRoute: typeof ExamplesSwipePinDismissRoute;
  ExamplesTailwindStyledRoute: typeof ExamplesTailwindStyledRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/tailwind-styled": {
      id: "/examples/tailwind-styled";
      path: "/examples/tailwind-styled";
      fullPath: "/examples/tailwind-styled";
      preLoaderRoute: typeof ExamplesTailwindStyledRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/swipe-pin-dismiss": {
      id: "/examples/swipe-pin-dismiss";
      path: "/examples/swipe-pin-dismiss";
      fullPath: "/examples/swipe-pin-dismiss";
      preLoaderRoute: typeof ExamplesSwipePinDismissRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/store-inspector": {
      id: "/examples/store-inspector";
      path: "/examples/store-inspector";
      fullPath: "/examples/store-inspector";
      preLoaderRoute: typeof ExamplesStoreInspectorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/stacked-deck": {
      id: "/examples/stacked-deck";
      path: "/examples/stacked-deck";
      fullPath: "/examples/stacked-deck";
      preLoaderRoute: typeof ExamplesStackedDeckRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/scrollable-tray": {
      id: "/examples/scrollable-tray";
      path: "/examples/scrollable-tray";
      fullPath: "/examples/scrollable-tray";
      preLoaderRoute: typeof ExamplesScrollableTrayRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/promise-lifecycle": {
      id: "/examples/promise-lifecycle";
      path: "/examples/promise-lifecycle";
      fullPath: "/examples/promise-lifecycle";
      preLoaderRoute: typeof ExamplesPromiseLifecycleRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/placements": {
      id: "/examples/placements";
      path: "/examples/placements";
      fullPath: "/examples/placements";
      preLoaderRoute: typeof ExamplesPlacementsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/persistent-toast": {
      id: "/examples/persistent-toast";
      path: "/examples/persistent-toast";
      fullPath: "/examples/persistent-toast";
      preLoaderRoute: typeof ExamplesPersistentToastRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/outside-react": {
      id: "/examples/outside-react";
      path: "/examples/outside-react";
      fullPath: "/examples/outside-react";
      preLoaderRoute: typeof ExamplesOutsideReactRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/multiple-containers": {
      id: "/examples/multiple-containers";
      path: "/examples/multiple-containers";
      fullPath: "/examples/multiple-containers";
      preLoaderRoute: typeof ExamplesMultipleContainersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/max-toasts": {
      id: "/examples/max-toasts";
      path: "/examples/max-toasts";
      fullPath: "/examples/max-toasts";
      preLoaderRoute: typeof ExamplesMaxToastsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/inline-sidebar": {
      id: "/examples/inline-sidebar";
      path: "/examples/inline-sidebar";
      fullPath: "/examples/inline-sidebar";
      preLoaderRoute: typeof ExamplesInlineSidebarRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/framer-motion": {
      id: "/examples/framer-motion";
      path: "/examples/framer-motion";
      fullPath: "/examples/framer-motion";
      preLoaderRoute: typeof ExamplesFramerMotionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/form-validation": {
      id: "/examples/form-validation";
      path: "/examples/form-validation";
      fullPath: "/examples/form-validation";
      preLoaderRoute: typeof ExamplesFormValidationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/floating-anchor": {
      id: "/examples/floating-anchor";
      path: "/examples/floating-anchor";
      fullPath: "/examples/floating-anchor";
      preLoaderRoute: typeof ExamplesFloatingAnchorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/duplicate-id": {
      id: "/examples/duplicate-id";
      path: "/examples/duplicate-id";
      fullPath: "/examples/duplicate-id";
      preLoaderRoute: typeof ExamplesDuplicateIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/drag-to-dismiss": {
      id: "/examples/drag-to-dismiss";
      path: "/examples/drag-to-dismiss";
      fullPath: "/examples/drag-to-dismiss";
      preLoaderRoute: typeof ExamplesDragToDismissRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/drag-reposition": {
      id: "/examples/drag-reposition";
      path: "/examples/drag-reposition";
      fullPath: "/examples/drag-reposition";
      preLoaderRoute: typeof ExamplesDragRepositionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/custom-component": {
      id: "/examples/custom-component";
      path: "/examples/custom-component";
      fullPath: "/examples/custom-component";
      preLoaderRoute: typeof ExamplesCustomComponentRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/countdown-progress": {
      id: "/examples/countdown-progress";
      path: "/examples/countdown-progress";
      fullPath: "/examples/countdown-progress";
      preLoaderRoute: typeof ExamplesCountdownProgressRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/basic-variants": {
      id: "/examples/basic-variants";
      path: "/examples/basic-variants";
      fullPath: "/examples/basic-variants";
      preLoaderRoute: typeof ExamplesBasicVariantsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/animation-wrapper": {
      id: "/examples/animation-wrapper";
      path: "/examples/animation-wrapper";
      fullPath: "/examples/animation-wrapper";
      preLoaderRoute: typeof ExamplesAnimationWrapperRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesAnimationWrapperRoute: ExamplesAnimationWrapperRoute,
  ExamplesBasicVariantsRoute: ExamplesBasicVariantsRoute,
  ExamplesCountdownProgressRoute: ExamplesCountdownProgressRoute,
  ExamplesCustomComponentRoute: ExamplesCustomComponentRoute,
  ExamplesDragRepositionRoute: ExamplesDragRepositionRoute,
  ExamplesDragToDismissRoute: ExamplesDragToDismissRoute,
  ExamplesDuplicateIdRoute: ExamplesDuplicateIdRoute,
  ExamplesFloatingAnchorRoute: ExamplesFloatingAnchorRoute,
  ExamplesFormValidationRoute: ExamplesFormValidationRoute,
  ExamplesFramerMotionRoute: ExamplesFramerMotionRoute,
  ExamplesInlineSidebarRoute: ExamplesInlineSidebarRoute,
  ExamplesMaxToastsRoute: ExamplesMaxToastsRoute,
  ExamplesMultipleContainersRoute: ExamplesMultipleContainersRoute,
  ExamplesOutsideReactRoute: ExamplesOutsideReactRoute,
  ExamplesPersistentToastRoute: ExamplesPersistentToastRoute,
  ExamplesPlacementsRoute: ExamplesPlacementsRoute,
  ExamplesPromiseLifecycleRoute: ExamplesPromiseLifecycleRoute,
  ExamplesScrollableTrayRoute: ExamplesScrollableTrayRoute,
  ExamplesStackedDeckRoute: ExamplesStackedDeckRoute,
  ExamplesStoreInspectorRoute: ExamplesStoreInspectorRoute,
  ExamplesSwipePinDismissRoute: ExamplesSwipePinDismissRoute,
  ExamplesTailwindStyledRoute: ExamplesTailwindStyledRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
