name: Quality checks

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Type-check
        run: pnpm lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Run tests
        run: pnpm test
